// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: P.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PlayerInfo {

  /// <summary>Holder for reflection information generated from P.proto</summary>
  public static partial class PReflection {

    #region Descriptor
    /// <summary>File descriptor for P.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgdQLnByb3RvEgpwbGF5ZXJJbmZvIpEBCgRtb3ZlEiUKCHBvc2l0aW9uGAEg",
            "ASgLMhMucGxheWVySW5mby52ZWN0b3IzEiUKCHJvdGF0aW9uGAIgASgLMhMu",
            "cGxheWVySW5mby52ZWN0b3IzEiUKCHZlbG9jaXR5GAMgASgLMhMucGxheWVy",
            "SW5mby52ZWN0b3IzEgkKAWgYBCABKAISCQoBdhgFIAEoAiKCAgoOQ2hhcmFj",
            "dGVyU3RhdGUSJQoIcG9zaXRpb24YASABKAsyEy5wbGF5ZXJJbmZvLnZlY3Rv",
            "cjMSEQoJbW92ZW1lbnRYGAIgASgCEhEKCW1vdmVtZW50WRgDIAEoAhIMCgRq",
            "dW1wGAQgASgIEgsKA3J1bhgFIAEoCBIQCghpbnRlcmFjdBgGIAEoCBIMCgRy",
            "b2xsGAcgASgIEgwKBGxvY2sYCCABKAgSDgoGYXR0YWNrGAkgASgIEhMKC2hl",
            "YXZ5QXR0YWNrGAogASgIEg4KBmNyb3VjaBgLIAEoCBIOCgZvcGVuVUkYDCAB",
            "KAgSFQoNb3BlbkNvbnNvbGVVSRgNIAEoCCIqCgd2ZWN0b3IzEgkKAXgYASAB",
            "KAISCQoBeRgCIAEoAhIJCgF6GAMgASgCIhUKBHBpbmcSDQoFdGltZXIYASAB",
            "KAkiGQoJQW5pbWF0aW9uEgwKBG5hbWUYASABKAkiHAoGQWN0aW9uEhIKCmFj",
            "dGlvbm5hbWUYASABKAkilAEKBUxvZ2luEhQKDGxlZnRXZWFwb25pZBgBIAEo",
            "BRIVCg1yaWdodFdlYXBvbmlkGAIgASgFEg4KBmhlYWRpZBgDIAEoBRIOCgZi",
            "b2R5aWQYBCABKAUSEAoIdHJvdXNlcnMYBSABKAUSDQoFbGVnaWQYBiABKAUS",
            "DQoFYXJtaWQYByABKAUSDgoGaGFuZGlkGAggASgFIhwKDVBsYXllck1lc3Nh",
            "Z2USCwoDbWVzGAEgASgJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PlayerInfo.move), global::PlayerInfo.move.Parser, new[]{ "Position", "Rotation", "Velocity", "H", "V" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PlayerInfo.CharacterState), global::PlayerInfo.CharacterState.Parser, new[]{ "Position", "MovementX", "MovementY", "Jump", "Run", "Interact", "Roll", "Lock", "Attack", "HeavyAttack", "Crouch", "OpenUI", "OpenConsoleUI" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PlayerInfo.vector3), global::PlayerInfo.vector3.Parser, new[]{ "X", "Y", "Z" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PlayerInfo.ping), global::PlayerInfo.ping.Parser, new[]{ "Timer" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PlayerInfo.Animation), global::PlayerInfo.Animation.Parser, new[]{ "Name" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PlayerInfo.Action), global::PlayerInfo.Action.Parser, new[]{ "Actionname" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PlayerInfo.Login), global::PlayerInfo.Login.Parser, new[]{ "LeftWeaponid", "RightWeaponid", "Headid", "Bodyid", "Trousers", "Legid", "Armid", "Handid" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PlayerInfo.PlayerMessage), global::PlayerInfo.PlayerMessage.Parser, new[]{ "Mes" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///protoc --csharp_out=. P.proto
  /// </summary>
  public sealed partial class move : pb::IMessage<move> {
    private static readonly pb::MessageParser<move> _parser = new pb::MessageParser<move>(() => new move());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<move> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PlayerInfo.PReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public move() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public move(move other) : this() {
      Position = other.position_ != null ? other.Position.Clone() : null;
      Rotation = other.rotation_ != null ? other.Rotation.Clone() : null;
      Velocity = other.velocity_ != null ? other.Velocity.Clone() : null;
      h_ = other.h_;
      v_ = other.v_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public move Clone() {
      return new move(this);
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 1;
    private global::PlayerInfo.vector3 position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::PlayerInfo.vector3 Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "rotation" field.</summary>
    public const int RotationFieldNumber = 2;
    private global::PlayerInfo.vector3 rotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::PlayerInfo.vector3 Rotation {
      get { return rotation_; }
      set {
        rotation_ = value;
      }
    }

    /// <summary>Field number for the "velocity" field.</summary>
    public const int VelocityFieldNumber = 3;
    private global::PlayerInfo.vector3 velocity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::PlayerInfo.vector3 Velocity {
      get { return velocity_; }
      set {
        velocity_ = value;
      }
    }

    /// <summary>Field number for the "h" field.</summary>
    public const int HFieldNumber = 4;
    private float h_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float H {
      get { return h_; }
      set {
        h_ = value;
      }
    }

    /// <summary>Field number for the "v" field.</summary>
    public const int VFieldNumber = 5;
    private float v_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float V {
      get { return v_; }
      set {
        v_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as move);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(move other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Position, other.Position)) return false;
      if (!object.Equals(Rotation, other.Rotation)) return false;
      if (!object.Equals(Velocity, other.Velocity)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(H, other.H)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(V, other.V)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (position_ != null) hash ^= Position.GetHashCode();
      if (rotation_ != null) hash ^= Rotation.GetHashCode();
      if (velocity_ != null) hash ^= Velocity.GetHashCode();
      if (H != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(H);
      if (V != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(V);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (position_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Position);
      }
      if (rotation_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Rotation);
      }
      if (velocity_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Velocity);
      }
      if (H != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(H);
      }
      if (V != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(V);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (rotation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rotation);
      }
      if (velocity_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Velocity);
      }
      if (H != 0F) {
        size += 1 + 4;
      }
      if (V != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(move other) {
      if (other == null) {
        return;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          position_ = new global::PlayerInfo.vector3();
        }
        Position.MergeFrom(other.Position);
      }
      if (other.rotation_ != null) {
        if (rotation_ == null) {
          rotation_ = new global::PlayerInfo.vector3();
        }
        Rotation.MergeFrom(other.Rotation);
      }
      if (other.velocity_ != null) {
        if (velocity_ == null) {
          velocity_ = new global::PlayerInfo.vector3();
        }
        Velocity.MergeFrom(other.Velocity);
      }
      if (other.H != 0F) {
        H = other.H;
      }
      if (other.V != 0F) {
        V = other.V;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (position_ == null) {
              position_ = new global::PlayerInfo.vector3();
            }
            input.ReadMessage(position_);
            break;
          }
          case 18: {
            if (rotation_ == null) {
              rotation_ = new global::PlayerInfo.vector3();
            }
            input.ReadMessage(rotation_);
            break;
          }
          case 26: {
            if (velocity_ == null) {
              velocity_ = new global::PlayerInfo.vector3();
            }
            input.ReadMessage(velocity_);
            break;
          }
          case 37: {
            H = input.ReadFloat();
            break;
          }
          case 45: {
            V = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 角色同步（替代 move）
  /// </summary>
  public sealed partial class CharacterState : pb::IMessage<CharacterState> {
    private static readonly pb::MessageParser<CharacterState> _parser = new pb::MessageParser<CharacterState>(() => new CharacterState());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CharacterState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PlayerInfo.PReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CharacterState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CharacterState(CharacterState other) : this() {
      Position = other.position_ != null ? other.Position.Clone() : null;
      movementX_ = other.movementX_;
      movementY_ = other.movementY_;
      jump_ = other.jump_;
      run_ = other.run_;
      interact_ = other.interact_;
      roll_ = other.roll_;
      lock_ = other.lock_;
      attack_ = other.attack_;
      heavyAttack_ = other.heavyAttack_;
      crouch_ = other.crouch_;
      openUI_ = other.openUI_;
      openConsoleUI_ = other.openConsoleUI_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CharacterState Clone() {
      return new CharacterState(this);
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 1;
    private global::PlayerInfo.vector3 position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::PlayerInfo.vector3 Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "movementX" field.</summary>
    public const int MovementXFieldNumber = 2;
    private float movementX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float MovementX {
      get { return movementX_; }
      set {
        movementX_ = value;
      }
    }

    /// <summary>Field number for the "movementY" field.</summary>
    public const int MovementYFieldNumber = 3;
    private float movementY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float MovementY {
      get { return movementY_; }
      set {
        movementY_ = value;
      }
    }

    /// <summary>Field number for the "jump" field.</summary>
    public const int JumpFieldNumber = 4;
    private bool jump_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Jump {
      get { return jump_; }
      set {
        jump_ = value;
      }
    }

    /// <summary>Field number for the "run" field.</summary>
    public const int RunFieldNumber = 5;
    private bool run_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Run {
      get { return run_; }
      set {
        run_ = value;
      }
    }

    /// <summary>Field number for the "interact" field.</summary>
    public const int InteractFieldNumber = 6;
    private bool interact_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Interact {
      get { return interact_; }
      set {
        interact_ = value;
      }
    }

    /// <summary>Field number for the "roll" field.</summary>
    public const int RollFieldNumber = 7;
    private bool roll_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Roll {
      get { return roll_; }
      set {
        roll_ = value;
      }
    }

    /// <summary>Field number for the "lock" field.</summary>
    public const int LockFieldNumber = 8;
    private bool lock_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Lock {
      get { return lock_; }
      set {
        lock_ = value;
      }
    }

    /// <summary>Field number for the "attack" field.</summary>
    public const int AttackFieldNumber = 9;
    private bool attack_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Attack {
      get { return attack_; }
      set {
        attack_ = value;
      }
    }

    /// <summary>Field number for the "heavyAttack" field.</summary>
    public const int HeavyAttackFieldNumber = 10;
    private bool heavyAttack_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HeavyAttack {
      get { return heavyAttack_; }
      set {
        heavyAttack_ = value;
      }
    }

    /// <summary>Field number for the "crouch" field.</summary>
    public const int CrouchFieldNumber = 11;
    private bool crouch_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Crouch {
      get { return crouch_; }
      set {
        crouch_ = value;
      }
    }

    /// <summary>Field number for the "openUI" field.</summary>
    public const int OpenUIFieldNumber = 12;
    private bool openUI_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool OpenUI {
      get { return openUI_; }
      set {
        openUI_ = value;
      }
    }

    /// <summary>Field number for the "openConsoleUI" field.</summary>
    public const int OpenConsoleUIFieldNumber = 13;
    private bool openConsoleUI_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool OpenConsoleUI {
      get { return openConsoleUI_; }
      set {
        openConsoleUI_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CharacterState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CharacterState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Position, other.Position)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MovementX, other.MovementX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MovementY, other.MovementY)) return false;
      if (Jump != other.Jump) return false;
      if (Run != other.Run) return false;
      if (Interact != other.Interact) return false;
      if (Roll != other.Roll) return false;
      if (Lock != other.Lock) return false;
      if (Attack != other.Attack) return false;
      if (HeavyAttack != other.HeavyAttack) return false;
      if (Crouch != other.Crouch) return false;
      if (OpenUI != other.OpenUI) return false;
      if (OpenConsoleUI != other.OpenConsoleUI) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (position_ != null) hash ^= Position.GetHashCode();
      if (MovementX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MovementX);
      if (MovementY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MovementY);
      if (Jump != false) hash ^= Jump.GetHashCode();
      if (Run != false) hash ^= Run.GetHashCode();
      if (Interact != false) hash ^= Interact.GetHashCode();
      if (Roll != false) hash ^= Roll.GetHashCode();
      if (Lock != false) hash ^= Lock.GetHashCode();
      if (Attack != false) hash ^= Attack.GetHashCode();
      if (HeavyAttack != false) hash ^= HeavyAttack.GetHashCode();
      if (Crouch != false) hash ^= Crouch.GetHashCode();
      if (OpenUI != false) hash ^= OpenUI.GetHashCode();
      if (OpenConsoleUI != false) hash ^= OpenConsoleUI.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (position_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Position);
      }
      if (MovementX != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(MovementX);
      }
      if (MovementY != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(MovementY);
      }
      if (Jump != false) {
        output.WriteRawTag(32);
        output.WriteBool(Jump);
      }
      if (Run != false) {
        output.WriteRawTag(40);
        output.WriteBool(Run);
      }
      if (Interact != false) {
        output.WriteRawTag(48);
        output.WriteBool(Interact);
      }
      if (Roll != false) {
        output.WriteRawTag(56);
        output.WriteBool(Roll);
      }
      if (Lock != false) {
        output.WriteRawTag(64);
        output.WriteBool(Lock);
      }
      if (Attack != false) {
        output.WriteRawTag(72);
        output.WriteBool(Attack);
      }
      if (HeavyAttack != false) {
        output.WriteRawTag(80);
        output.WriteBool(HeavyAttack);
      }
      if (Crouch != false) {
        output.WriteRawTag(88);
        output.WriteBool(Crouch);
      }
      if (OpenUI != false) {
        output.WriteRawTag(96);
        output.WriteBool(OpenUI);
      }
      if (OpenConsoleUI != false) {
        output.WriteRawTag(104);
        output.WriteBool(OpenConsoleUI);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (MovementX != 0F) {
        size += 1 + 4;
      }
      if (MovementY != 0F) {
        size += 1 + 4;
      }
      if (Jump != false) {
        size += 1 + 1;
      }
      if (Run != false) {
        size += 1 + 1;
      }
      if (Interact != false) {
        size += 1 + 1;
      }
      if (Roll != false) {
        size += 1 + 1;
      }
      if (Lock != false) {
        size += 1 + 1;
      }
      if (Attack != false) {
        size += 1 + 1;
      }
      if (HeavyAttack != false) {
        size += 1 + 1;
      }
      if (Crouch != false) {
        size += 1 + 1;
      }
      if (OpenUI != false) {
        size += 1 + 1;
      }
      if (OpenConsoleUI != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CharacterState other) {
      if (other == null) {
        return;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          position_ = new global::PlayerInfo.vector3();
        }
        Position.MergeFrom(other.Position);
      }
      if (other.MovementX != 0F) {
        MovementX = other.MovementX;
      }
      if (other.MovementY != 0F) {
        MovementY = other.MovementY;
      }
      if (other.Jump != false) {
        Jump = other.Jump;
      }
      if (other.Run != false) {
        Run = other.Run;
      }
      if (other.Interact != false) {
        Interact = other.Interact;
      }
      if (other.Roll != false) {
        Roll = other.Roll;
      }
      if (other.Lock != false) {
        Lock = other.Lock;
      }
      if (other.Attack != false) {
        Attack = other.Attack;
      }
      if (other.HeavyAttack != false) {
        HeavyAttack = other.HeavyAttack;
      }
      if (other.Crouch != false) {
        Crouch = other.Crouch;
      }
      if (other.OpenUI != false) {
        OpenUI = other.OpenUI;
      }
      if (other.OpenConsoleUI != false) {
        OpenConsoleUI = other.OpenConsoleUI;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (position_ == null) {
              position_ = new global::PlayerInfo.vector3();
            }
            input.ReadMessage(position_);
            break;
          }
          case 21: {
            MovementX = input.ReadFloat();
            break;
          }
          case 29: {
            MovementY = input.ReadFloat();
            break;
          }
          case 32: {
            Jump = input.ReadBool();
            break;
          }
          case 40: {
            Run = input.ReadBool();
            break;
          }
          case 48: {
            Interact = input.ReadBool();
            break;
          }
          case 56: {
            Roll = input.ReadBool();
            break;
          }
          case 64: {
            Lock = input.ReadBool();
            break;
          }
          case 72: {
            Attack = input.ReadBool();
            break;
          }
          case 80: {
            HeavyAttack = input.ReadBool();
            break;
          }
          case 88: {
            Crouch = input.ReadBool();
            break;
          }
          case 96: {
            OpenUI = input.ReadBool();
            break;
          }
          case 104: {
            OpenConsoleUI = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class vector3 : pb::IMessage<vector3> {
    private static readonly pb::MessageParser<vector3> _parser = new pb::MessageParser<vector3>(() => new vector3());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<vector3> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PlayerInfo.PReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public vector3() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public vector3(vector3 other) : this() {
      x_ = other.x_;
      y_ = other.y_;
      z_ = other.z_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public vector3 Clone() {
      return new vector3(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 1;
    private float x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 2;
    private float y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    /// <summary>Field number for the "z" field.</summary>
    public const int ZFieldNumber = 3;
    private float z_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Z {
      get { return z_; }
      set {
        z_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as vector3);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(vector3 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
      if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
      if (Z != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (X != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Y);
      }
      if (Z != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Z);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (X != 0F) {
        size += 1 + 4;
      }
      if (Y != 0F) {
        size += 1 + 4;
      }
      if (Z != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(vector3 other) {
      if (other == null) {
        return;
      }
      if (other.X != 0F) {
        X = other.X;
      }
      if (other.Y != 0F) {
        Y = other.Y;
      }
      if (other.Z != 0F) {
        Z = other.Z;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            X = input.ReadFloat();
            break;
          }
          case 21: {
            Y = input.ReadFloat();
            break;
          }
          case 29: {
            Z = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ping : pb::IMessage<ping> {
    private static readonly pb::MessageParser<ping> _parser = new pb::MessageParser<ping>(() => new ping());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ping> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PlayerInfo.PReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ping() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ping(ping other) : this() {
      timer_ = other.timer_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ping Clone() {
      return new ping(this);
    }

    /// <summary>Field number for the "timer" field.</summary>
    public const int TimerFieldNumber = 1;
    private string timer_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Timer {
      get { return timer_; }
      set {
        timer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ping);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ping other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Timer != other.Timer) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Timer.Length != 0) hash ^= Timer.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Timer.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Timer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Timer.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Timer);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ping other) {
      if (other == null) {
        return;
      }
      if (other.Timer.Length != 0) {
        Timer = other.Timer;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Timer = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Animation : pb::IMessage<Animation> {
    private static readonly pb::MessageParser<Animation> _parser = new pb::MessageParser<Animation>(() => new Animation());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Animation> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PlayerInfo.PReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Animation() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Animation(Animation other) : this() {
      name_ = other.name_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Animation Clone() {
      return new Animation(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Animation);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Animation other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Animation other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Action : pb::IMessage<Action> {
    private static readonly pb::MessageParser<Action> _parser = new pb::MessageParser<Action>(() => new Action());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Action> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PlayerInfo.PReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Action() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Action(Action other) : this() {
      actionname_ = other.actionname_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Action Clone() {
      return new Action(this);
    }

    /// <summary>Field number for the "actionname" field.</summary>
    public const int ActionnameFieldNumber = 1;
    private string actionname_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Actionname {
      get { return actionname_; }
      set {
        actionname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Action);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Action other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Actionname != other.Actionname) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Actionname.Length != 0) hash ^= Actionname.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Actionname.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Actionname);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Actionname.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Actionname);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Action other) {
      if (other == null) {
        return;
      }
      if (other.Actionname.Length != 0) {
        Actionname = other.Actionname;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Actionname = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Login : pb::IMessage<Login> {
    private static readonly pb::MessageParser<Login> _parser = new pb::MessageParser<Login>(() => new Login());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Login> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PlayerInfo.PReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Login() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Login(Login other) : this() {
      leftWeaponid_ = other.leftWeaponid_;
      rightWeaponid_ = other.rightWeaponid_;
      headid_ = other.headid_;
      bodyid_ = other.bodyid_;
      trousers_ = other.trousers_;
      legid_ = other.legid_;
      armid_ = other.armid_;
      handid_ = other.handid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Login Clone() {
      return new Login(this);
    }

    /// <summary>Field number for the "leftWeaponid" field.</summary>
    public const int LeftWeaponidFieldNumber = 1;
    private int leftWeaponid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int LeftWeaponid {
      get { return leftWeaponid_; }
      set {
        leftWeaponid_ = value;
      }
    }

    /// <summary>Field number for the "rightWeaponid" field.</summary>
    public const int RightWeaponidFieldNumber = 2;
    private int rightWeaponid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RightWeaponid {
      get { return rightWeaponid_; }
      set {
        rightWeaponid_ = value;
      }
    }

    /// <summary>Field number for the "headid" field.</summary>
    public const int HeadidFieldNumber = 3;
    private int headid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Headid {
      get { return headid_; }
      set {
        headid_ = value;
      }
    }

    /// <summary>Field number for the "bodyid" field.</summary>
    public const int BodyidFieldNumber = 4;
    private int bodyid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Bodyid {
      get { return bodyid_; }
      set {
        bodyid_ = value;
      }
    }

    /// <summary>Field number for the "trousers" field.</summary>
    public const int TrousersFieldNumber = 5;
    private int trousers_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Trousers {
      get { return trousers_; }
      set {
        trousers_ = value;
      }
    }

    /// <summary>Field number for the "legid" field.</summary>
    public const int LegidFieldNumber = 6;
    private int legid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Legid {
      get { return legid_; }
      set {
        legid_ = value;
      }
    }

    /// <summary>Field number for the "armid" field.</summary>
    public const int ArmidFieldNumber = 7;
    private int armid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Armid {
      get { return armid_; }
      set {
        armid_ = value;
      }
    }

    /// <summary>Field number for the "handid" field.</summary>
    public const int HandidFieldNumber = 8;
    private int handid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Handid {
      get { return handid_; }
      set {
        handid_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Login);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Login other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LeftWeaponid != other.LeftWeaponid) return false;
      if (RightWeaponid != other.RightWeaponid) return false;
      if (Headid != other.Headid) return false;
      if (Bodyid != other.Bodyid) return false;
      if (Trousers != other.Trousers) return false;
      if (Legid != other.Legid) return false;
      if (Armid != other.Armid) return false;
      if (Handid != other.Handid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LeftWeaponid != 0) hash ^= LeftWeaponid.GetHashCode();
      if (RightWeaponid != 0) hash ^= RightWeaponid.GetHashCode();
      if (Headid != 0) hash ^= Headid.GetHashCode();
      if (Bodyid != 0) hash ^= Bodyid.GetHashCode();
      if (Trousers != 0) hash ^= Trousers.GetHashCode();
      if (Legid != 0) hash ^= Legid.GetHashCode();
      if (Armid != 0) hash ^= Armid.GetHashCode();
      if (Handid != 0) hash ^= Handid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LeftWeaponid != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(LeftWeaponid);
      }
      if (RightWeaponid != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(RightWeaponid);
      }
      if (Headid != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Headid);
      }
      if (Bodyid != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Bodyid);
      }
      if (Trousers != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Trousers);
      }
      if (Legid != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Legid);
      }
      if (Armid != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Armid);
      }
      if (Handid != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Handid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LeftWeaponid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LeftWeaponid);
      }
      if (RightWeaponid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RightWeaponid);
      }
      if (Headid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Headid);
      }
      if (Bodyid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Bodyid);
      }
      if (Trousers != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Trousers);
      }
      if (Legid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Legid);
      }
      if (Armid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Armid);
      }
      if (Handid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Handid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Login other) {
      if (other == null) {
        return;
      }
      if (other.LeftWeaponid != 0) {
        LeftWeaponid = other.LeftWeaponid;
      }
      if (other.RightWeaponid != 0) {
        RightWeaponid = other.RightWeaponid;
      }
      if (other.Headid != 0) {
        Headid = other.Headid;
      }
      if (other.Bodyid != 0) {
        Bodyid = other.Bodyid;
      }
      if (other.Trousers != 0) {
        Trousers = other.Trousers;
      }
      if (other.Legid != 0) {
        Legid = other.Legid;
      }
      if (other.Armid != 0) {
        Armid = other.Armid;
      }
      if (other.Handid != 0) {
        Handid = other.Handid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LeftWeaponid = input.ReadInt32();
            break;
          }
          case 16: {
            RightWeaponid = input.ReadInt32();
            break;
          }
          case 24: {
            Headid = input.ReadInt32();
            break;
          }
          case 32: {
            Bodyid = input.ReadInt32();
            break;
          }
          case 40: {
            Trousers = input.ReadInt32();
            break;
          }
          case 48: {
            Legid = input.ReadInt32();
            break;
          }
          case 56: {
            Armid = input.ReadInt32();
            break;
          }
          case 64: {
            Handid = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PlayerMessage : pb::IMessage<PlayerMessage> {
    private static readonly pb::MessageParser<PlayerMessage> _parser = new pb::MessageParser<PlayerMessage>(() => new PlayerMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlayerMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PlayerInfo.PReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerMessage(PlayerMessage other) : this() {
      mes_ = other.mes_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerMessage Clone() {
      return new PlayerMessage(this);
    }

    /// <summary>Field number for the "mes" field.</summary>
    public const int MesFieldNumber = 1;
    private string mes_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mes {
      get { return mes_; }
      set {
        mes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlayerMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlayerMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Mes != other.Mes) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Mes.Length != 0) hash ^= Mes.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Mes.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Mes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Mes.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mes);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlayerMessage other) {
      if (other == null) {
        return;
      }
      if (other.Mes.Length != 0) {
        Mes = other.Mes;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Mes = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
